spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tsxmdb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
